version: '3.8'

services:
  microfluidica-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app/Python
      - R_HOME=/usr/lib/R
      - R_LIBS_USER=/usr/local/lib/R/site-library
    # volumes:
      # - ./Python:/app/Python
      # - ./DNAr:/app/DNAr
      # - ./frontend/new-interface:/app/frontend
    restart: unless-stopped
