# rm(list = ls())

source('R/parser.R')
source('R/util_functions.R')
source('R/crn_reactor.R')
source('R/4domain_reactor.R')
source('R/io.R')

source('R/GATE_LIB.R')
source('R/ANALOG_GATE_LIB.R')
source('R/ELECTRO_LIB.R')
source('R/ELECTRO_SIM.R')

source('R/forced_concentrations.R')


# ============================================================
# Parameters
# ============================================================

timing <- seq(0, 60, by = 0.01)

rate <- 1

# Fixed capacitance
capacitance <- 10

# Resistances to compare
resistances <- c(1, 2, 4)


# ============================================================
# Build an RC circuit for a given resistance
# ============================================================

Make_RC <- function(timing, resistance, id) {
  # Base circuit
  circuit <- make_circuit(timing)
  
  # Create capacitor/RC component
  cap <- Make_Capacitor_Component(
    id,
    capacitance,
    resistance
  )

  # Input voltage connected to RC input
  cap$il$voltage_positive <- 'v_in'
  
  g_dalchau <- Make_Oscillator_Dalchau('sin', 'x', 'v_in', 'z', 1e-3, 1e-3, 15, 4e-1)
  c_comparator <- Make_Mux2_balanced(
    'mux1', 'x', 'v_in', 'low', 'high', 'comp_out',
    0, 0, 3, 8, 0, 7.0e-1
  )
  circuit <- circuit_add_gate(circuit, g_dalchau)
  circuit <- circuit_add_gate(circuit, c_comparator)

  # Compile RC gate
  rc_gate <- Make_Circuit_RC(
    cap$name,
    cap$il,
    cap$ol,
    cap$ic,
    rate
  )



  # Add RC gate
  circuit <- circuit_add_compile_gates(
    circuit,
    rc_gate
  )

  return(circuit)
}


# ============================================================
# Input voltage
# ============================================================

forced_concentrations <- list(
  v_in = function(t)
    square_input(
      t,
      pulse_width = 30,
      period = 60,
      amplitude = 10
    )
)


# ============================================================
# Storage for all simulations
# ============================================================

behavior <- data.frame(
  time = timing
)

all_results <- list()


# ============================================================
# Simulate each resistance
# ============================================================

for (i in seq_along(resistances)) {

  resistance <- resistances[i]

  cat(sprintf(
    "Simulating RC circuit: R = %.3f, C = %.3f\n",
    resistance,
    capacitance
  ))

  circuit <- Make_RC(
    timing = timing,
    resistance = resistance,
    id = i - 1
  )

  # ----------------------------------------------------------
  # CRN / DSD simulation
  # ----------------------------------------------------------

  result <- React_circuit(
    circuit,
    # forced_concentrations = forced_concentrations,
    engine = 'diffeqr'
  )

  all_results[[i]] <- result


  # ----------------------------------------------------------
  # Identify output voltage of this RC component
  #
  # Component names generated by Make_Capacitor_Component()
  # follow the c0, c1, c2, ... convention.
  # ----------------------------------------------------------

  component_name <- paste0("c", i - 1)

  v_positive <- paste0(component_name, "ol_vp")
  v_negative <- paste0(component_name, "ol_vn")


  # ----------------------------------------------------------
  # CRN capacitor voltage
  # ----------------------------------------------------------

  vc_crn <- result[[v_positive]] -
             result[[v_negative]]


  # ----------------------------------------------------------
  # Analytical RC simulation
  # ----------------------------------------------------------

  simRC <- simulate_sRC_voltage_source(
    timing,
    result[['v_in']],
    resistance,
    capacitance
  )


  # ----------------------------------------------------------
  # Store input only once
  # ----------------------------------------------------------

  if (!"v_in" %in% names(behavior)) {
    behavior[["v_in"]] <- result[['v_in']]
  }


  # ----------------------------------------------------------
  # Store CRN and analytical responses
  # ----------------------------------------------------------

  behavior[[jn(
    "vc_R",
    resistance
  )]] <- vc_crn

  behavior[[jn(
    "V(C)_R",
    resistance
  )]] <- simRC$capacitor_voltage

  behavior[[jn(
    "I(R,C)_R",
    resistance
  )]] <- simRC$current_output


  # ----------------------------------------------------------
  # Metrics
  # ----------------------------------------------------------

#   metrics <- analyze_transient_metrics(
#     timing = timing,
#     v_in = behavior[["v_in"]],
#     vc_model = vc_crn,
#     vc_sim = simRC$capacitor_voltage,
#     t0 = 10,
#     t1 = 25,
#     resistance = resistance,
#     inductance = 0,
#     capacitance = capacitance
#   )

  cat(sprintf("\nMetrics for R = %.3f:\n", resistance))
#   print(metrics)
}


# ============================================================
# Plot capacitor voltage
# ============================================================

crn_species <- sapply(
  resistances,
  function(R) jn("vc_R", R)
)

reference_species <- sapply(
  resistances,
  function(R) jn("V(C)_R", R)
)


plot_behavior(
  behavior,
  title = sprintf(
    "RC Response DSD Vin = 10[V], C = 10[mF]",
    capacitance
  ),
  species = c(
    "v_in",
    crn_species
  ),
  species_dotted = reference_species
)