---
config:
  theme: redux
  layout: dagre
---
flowchart LR
    vin["$$v_{in}$$"] --> Mul1[["Mul1"]]
    1ol["$$ 1/L $$"] --> Mul1
    Mul1 -- $$\frac{1}{L}v_{in}$$ --> Add3{"Add3"}
    Add3 -- "$$-\frac{R}{L} x_1 - \frac{1}{L}x_2 + \frac{1}{L}v_{in}$$" --> Int1[["Int1"]]
    Int1 -- "$$\int -\frac{R}{L} x_1 - \frac{1}{L}x_2 + \frac{1}{L}v_{in}$$" --> X1["$$x_1:i$$"]
    X1 --> Mul2[["Mul2"]] & Mul3[["Mul3"]]
    mrol["$$ -R/L $$"] --> Mul2
    Mul2 -- "$$-\frac{R}{L}x_1$$" --> Add3
    ioc["$$ 1/C $$"] --> Mul3
    Mul3 -- $$\frac{1}{C}i$$ --> Int2[["Int2"]]
    Int2 -- $$\int \frac{1}{C} i$$ --> X2["$$x_2:v_c$$"]
    X2 --> Mul4[["Mul4"]]
    m1ol["$$ -1/L $$"] --> Mul4
    Mul4 -- "$$\frac{-1}{L} v_c$$" --> Add3
    vin@{ shape: lean-r}
    1ol@{ shape: lean-r}
    X1@{ shape: lean-l}
    mrol@{ shape: lean-r}
    ioc@{ shape: lean-r}
    X2@{ shape: lean-l}
    m1ol@{ shape: lean-r}


graph LR
  %% Base inductor production
  l1il_vp --|k1|--> l1ol_ip
  l1il_vp --|k2 1/RC|--> l1ol_vp
  l1il_vn --|k1|--> l1ol_in
  l1il_vn --|k2 1/RC|--> l1ol_vn

  %% l1ol interconversions
  l1ol_vn --|k3|--> l1ol_vp
  l1ol_vp --|k3|--> l1ol_vn

  %% l1ol_ip/in interactions
  l1ol_in --|k1|--> l1ol_ip
  l1ol_ip --|k1|--> l1ol_in

  %% Cross interactions
  l1ol_in --|k2 1/RC|--> l1ol_vp
  l1ol_ip --|k2 1/RC|--> l1ol_vn

  %% Degradation sinks
  l1ol_ip --|k4|--> X
  l1ol_in --|k4|--> X
  l1ol_vp --|k4|--> X
  l1ol_vn --|k4|--> X

  %% Zero sink node
  X([$$\emptyset$$])

  l1il_vp([$$v_i^+$$])
  l1il_vn([$$v_i^-$$])
  l1ol_ip([$$i_o^+$$])
  l1ol_in([$$i_o^-$$])
  l1ol_vp([$$v_o^+$$])
  l1ol_vn([$$v_o^-$$])
